// This file is auto-generated by the tags preprocessor
const contributorsIndex = {
  "fredriksvantes": {
    "pages": [
      "awareness/core-awareness-principles.html",
      "awareness/cultivating-a-security-aware-mindset.html",
      "awareness/resources-and-further-reading.html",
      "awareness/staying-informed-and-continuous-learning.html",
      "awareness/understanding-threat-vectors.html",
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/telegram.html",
      "community-management/twitter.html"
    ],
    "roles": {
      "wrote": ["community-management/google.html", "awareness/cultivating-a-security-aware-mindset.html", "community-management/twitter.html", "community-management/telegram.html", "awareness/resources-and-further-reading.html", "awareness/understanding-threat-vectors.html", "community-management/discord.html", "awareness/core-awareness-principles.html", "awareness/staying-informed-and-continuous-learning.html"]
    },
    "company": "Ethereum Foundation",
    "avatar": "https://github.com/fredriksvantes.png",
    "github": "https://github.com/fredriksvantes",
    "twitter": "https://twitter.com/fredriksvantes",
    "website": "https://ethereum.org",
    "role": "Head of Security",
    "description": "Initial contributor to the Security Frameworks",
    "features": ["core"]
  },
  "ghadi8": {
    "pages": [
      "ens/cross-chain-compatibility.html",
      "ens/data-integrity-verification.html",
      "ens/index.html",
      "ens/interface-compliance.html",
      "ens/name-handling-normalization.html",
      "ens/smart-contract-integration.html"
    ],
    "roles": {
      "wrote": ["ens/index.html", "ens/data-integrity-verification.html", "ens/name-handling-normalization.html", "ens/cross-chain-compatibility.html", "ens/smart-contract-integration.html", "ens/interface-compliance.html"]
    },
    "company": "JustaLab",
    "avatar": "https://github.com/ghadi8.png",
    "github": "https://github.com/ghadi8",
    "website": "https://justalab.co",
    "description": "Creator and maintainer of the ENS framework",
    "features": ["steward"]
  },
  "mattaereal": {
    "pages": [
      "awareness/core-awareness-principles.html",
      "awareness/core-awareness-principles.html",
      "awareness/cultivating-a-security-aware-mindset.html",
      "awareness/cultivating-a-security-aware-mindset.html",
      "awareness/index.html",
      "awareness/index.html",
      "awareness/resources-and-further-reading.html",
      "awareness/resources-and-further-reading.html",
      "awareness/staying-informed-and-continuous-learning.html",
      "awareness/staying-informed-and-continuous-learning.html",
      "awareness/understanding-threat-vectors.html",
      "awareness/understanding-threat-vectors.html",
      "community-management/discord.html",
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/google.html",
      "community-management/index.html",
      "community-management/index.html",
      "community-management/telegram.html",
      "community-management/telegram.html",
      "community-management/twitter.html",
      "community-management/twitter.html"
    ],
    "roles": {
      "reviewed": ["community-management/google.html", "awareness/cultivating-a-security-aware-mindset.html", "community-management/twitter.html", "community-management/telegram.html", "awareness/resources-and-further-reading.html", "awareness/understanding-threat-vectors.html", "community-management/discord.html", "awareness/core-awareness-principles.html", "community-management/index.html", "awareness/index.html", "awareness/staying-informed-and-continuous-learning.html"],
      "wrote": ["community-management/google.html", "awareness/cultivating-a-security-aware-mindset.html", "community-management/twitter.html", "community-management/telegram.html", "awareness/resources-and-further-reading.html", "awareness/understanding-threat-vectors.html", "community-management/discord.html", "awareness/core-awareness-principles.html", "community-management/index.html", "awareness/index.html", "awareness/staying-informed-and-continuous-learning.html"]
    },
    "company": "The Red Guild | SEAL",
    "avatar": "https://github.com/mattaereal.png",
    "github": "https://github.com/mattaereal",
    "twitter": "https://twitter.com/mattaereal",
    "website": "https://theredguild.org",
    "role": "Security Knowmad",
    "description": "Initiative lead and maintainer",
    "features": ["lead"]
  },
  "nftdreww": {
    "pages": [
      "community-management/discord.html"
    ],
    "roles": {
      "fact_checked": ["community-management/discord.html"]
    },
    "company": "PocketUniverseZ",
    "avatar": "https://pbs.twimg.com/profile_images/1589726471249174536/pEqaw6FO_400x400.png",
    "github": "https://github.com/NFTDreww",
    "twitter": "https://twitter.com/nft_dreww",
    "role": "Security Researcher",
    "description": "Managing and curating the Community Management framework",
    "features": ["steward"]
  },
  "robert": {
    "pages": [
      "awareness/index.html",
      "community-management/index.html"
    ],
    "roles": {
      "reviewed": ["awareness/index.html"],
      "wrote": ["community-management/index.html"]
    },
    "company": "Skylock",
    "avatar": "https://github.com/Robert-MacWha.png",
    "github": "https://github.com/robert",
    "website": "https://robert.macwha.com/",
    "role": "Full-stack developer and security enthusiast",
    "description": "Web dev & fact checking",
    "features": ["core"]
  },
  "zedt3ster": {
    "pages": [
      "awareness/core-awareness-principles.html",
      "awareness/cultivating-a-security-aware-mindset.html",
      "awareness/resources-and-further-reading.html",
      "awareness/staying-informed-and-continuous-learning.html",
      "awareness/understanding-threat-vectors.html",
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/telegram.html",
      "community-management/twitter.html"
    ],
    "roles": {
      "wrote": ["community-management/google.html", "awareness/cultivating-a-security-aware-mindset.html", "community-management/twitter.html", "community-management/telegram.html", "awareness/resources-and-further-reading.html", "awareness/understanding-threat-vectors.html", "community-management/discord.html", "awareness/core-awareness-principles.html", "awareness/staying-informed-and-continuous-learning.html"]
    },
    "company": "Sigma Prime",
    "avatar": "https://github.com/zedt3ster.png",
    "github": "https://github.com/zedt3ster",
    "twitter": "https://twitter.com/ethzed",
    "website": "https://sigmaprime.io",
    "role": "Director. Ethereum enthusiast ",
    "description": "Initial contributor to the Security Frameworks",
    "features": ["core"]
  },
  "engn33r": {
    "pages": [],
    "github": "https://github.com/engn33r",
    "avatar": "https://github.com/engn33r.png",
    "twitter": "https://twitter.com/bl4ckb1rd71",
    "description": "Signing best practices",
    "features": ["featured"]
  },
  "tebayoso": {
    "pages": [],
    "github": "https://github.com/tebayoso",
    "avatar": "https://github.com/tebayoso.png",
    "twitter": "https://twitter.com/tebayoso",
    "company": "The Red Guild",
    "description": "Initial implementation of tag filtering",
    "features": ["featured"]
  }
};
