// This file is auto-generated by the tags preprocessor
const contributorsIndex = {
  "mattaereal": {
    "chapters": [
      "awareness/index.html",
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/index.html",
      "community-management/telegram.html",
      "community-management/twitter.html"
    ],
    "company": "The Red Guild | SEAL",
    "role": "Security Frameworks Lead",
    "description": "Initiative lead and maintainer of the Security Frameworks",
    "features": ["lead"]
  },
  "nftdreww": {
    "chapters": [
      "community-management/discord.html"
    ],
    "company": "Community DAO",
    "role": "Community Management",
    "description": "Managing and curating the Community Management framework",
    "features": ["steward"]
  },
  "robert": {
    "chapters": [
      "community-management/index.html"
    ],
    "company": "Skylock",
    "role": "Security Frameworks webs collaborator",
    "description": "Full-stack developer and security enthusiast",
    "features": ["core"]
  },
  "engn33r": {
    "chapters": [],
    "github": "https://github.com/engn33r",
    "avatar": "https://github.com/engn33r.png",
    "twitter": "https://twitter.com/bl4ckb1rd71",
    "description": "Signing best practices",
    "features": ["featured"]
  },
  "Fredrik Svantes": {
    "chapters": [],
    "github": "https://github.com/fredriksvantes",
    "avatar": "https://github.com/fredriksvantes.png",
    "twitter": "https://twitter.com/fredriksvantes",
    "website": "https://ethereum.org",
    "company": "Ethereum Foundation",
    "role": "Security Frameworks core",
    "description": "Initial contributor to the Security Frameworks",
    "features": ["core"]
  },
  "tebayoso": {
    "chapters": [],
    "github": "https://github.com/tebayoso",
    "avatar": "https://github.com/tebayoso.png",
    "twitter": "https://twitter.com/tebayoso",
    "company": "The Red Guild",
    "description": "Initial implementation of tag filtering",
    "features": ["featured"]
  },
  "zedt3ster": {
    "chapters": [],
    "github": "https://github.com/zedt3ster",
    "avatar": "https://github.com/zedt3ster.png",
    "twitter": "https://twitter.com/ethzed",
    "website": "https://sigmaprime.io",
    "company": "Sigma Prime",
    "role": "Security Frameworks core",
    "description": "Initial contributor to the Security Frameworks",
    "features": ["core"]
  }
};
