// This file is auto-generated by the tags preprocessor
const contributorsIndex = {
  "fredriksvantes": {
    "pages": [
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/telegram.html",
      "community-management/twitter.html"
    ],
    "roles": {
      "wrote": ["community-management/google.html", "community-management/discord.html", "community-management/twitter.html", "community-management/telegram.html"]
    },
    "company": "Ethereum Foundation",
    "avatar": "https://github.com/fredriksvantes.png",
    "github": "https://github.com/fredriksvantes",
    "twitter": "https://twitter.com/fredriksvantes",
    "website": "https://ethereum.org",
    "role": "Security Engineer",
    "description": "Initial contributor to the Security Frameworks",
    "features": ["core"]
  },
  "mattaereal": {
    "pages": [
      "awareness/index.html",
      "community-management/discord.html",
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/google.html",
      "community-management/index.html",
      "community-management/index.html",
      "community-management/telegram.html",
      "community-management/telegram.html",
      "community-management/twitter.html",
      "community-management/twitter.html"
    ],
    "roles": {
      "wrote": ["community-management/google.html", "community-management/index.html", "community-management/discord.html", "community-management/twitter.html", "community-management/telegram.html"],
      "reviewed": ["community-management/google.html", "community-management/index.html", "community-management/discord.html", "community-management/twitter.html", "community-management/telegram.html"]
    },
    "company": "The Red Guild | SEAL",
    "avatar": "https://github.com/mattaereal.png",
    "github": "https://github.com/mattaereal",
    "twitter": "https://twitter.com/mattaereal",
    "website": "https://theredguild.org",
    "role": "Security Researcher",
    "description": "Initiative lead and maintainer",
    "features": ["lead"]
  },
  "nftdreww": {
    "pages": [
      "community-management/discord.html"
    ],
    "roles": {
      "fact_checked": ["community-management/discord.html"]
    },
    "company": "DeFi Protocol",
    "avatar": "https://pbs.twimg.com/profile_images/1589726471249174536/pEqaw6FO_400x400.png",
    "github": "https://github.com/NFTDreww",
    "twitter": "https://twitter.com/nft_dreww",
    "role": "Security Researcher",
    "description": "Managing and curating the Community Management framework",
    "features": ["steward"]
  },
  "robert": {
    "pages": [
      "community-management/index.html"
    ],
    "roles": {
      "wrote": ["community-management/index.html"]
    },
    "company": "Blockchain Labs",
    "avatar": "https://github.com/Robert-MacWha.png",
    "github": "https://github.com/robert",
    "website": "https://robert.macwha.com/",
    "role": "Security Frameworks webs collaborator",
    "description": "Full-stack developer and security enthusiast",
    "features": ["core"]
  },
  "zedt3ster": {
    "pages": [
      "community-management/discord.html",
      "community-management/google.html",
      "community-management/telegram.html",
      "community-management/twitter.html"
    ],
    "roles": {
      "wrote": ["community-management/google.html", "community-management/discord.html", "community-management/twitter.html", "community-management/telegram.html"]
    },
    "company": "Web3 Security",
    "avatar": "https://github.com/zedt3ster.png",
    "github": "https://github.com/zedt3ster",
    "twitter": "https://twitter.com/ethzed",
    "website": "https://sigmaprime.io",
    "role": "Security Auditor",
    "description": "Initial contributor to the Security Frameworks",
    "features": ["core"]
  },
  "engn33r": {
    "pages": [],
    "github": "https://github.com/engn33r",
    "avatar": "https://github.com/engn33r.png",
    "twitter": "https://twitter.com/bl4ckb1rd71",
    "description": "Signing best practices",
    "features": ["featured"]
  },
  "tebayoso": {
    "pages": [],
    "github": "https://github.com/tebayoso",
    "avatar": "https://github.com/tebayoso.png",
    "twitter": "https://twitter.com/tebayoso",
    "company": "The Red Guild",
    "description": "Initial implementation of tag filtering",
    "features": ["featured"]
  }
};
