// AUTO-GENERATED by scripts/build-verified-mapping.mjs — do not edit manually
// LLM-verified mappings: each ref has been evaluated for substantive baseline coverage

export interface FrameworkRef {
  page: string;
  title: string;
  header: string | null;
  coverage: 'full' | 'partial';
}

export interface CertRef {
  controlId: string;
  controlTitle: string;
  certName: string;
  header: string | null;
  coverage: 'full' | 'partial';
}

/** Forward index: cert control ID → verified framework page references */
export const controlToFramework: Record<string, FrameworkRef[]> = {
  "di-1.1.1": [],
  "di-1.1.2": [],
  "di-1.1.3": [
    {
      "page": "/devsecops/integrated-development-environments",
      "title": "Securing Development Environments | SEAL",
      "header": null,
      "coverage": "partial"
    }
  ],
  "di-1.1.4": [
    {
      "page": "/devsecops/integrated-development-environments",
      "title": "Securing Development Environments | SEAL",
      "header": null,
      "coverage": "partial"
    }
  ],
  "di-2.1.1": [
    {
      "page": "/secure-software-development/secure-code-repositories-version-control",
      "title": "Secure Code Repositories & Version Control | SEAL",
      "header": "Best Practices for Secure Code Repositories",
      "coverage": "partial"
    }
  ],
  "di-2.1.2": [
    {
      "page": "/devsecops/continuous-integration-continuous-deployment",
      "title": "Securing CI/CD Pipelines | SEAL",
      "header": null,
      "coverage": "partial"
    }
  ],
  "di-2.1.3": [],
  "di-2.1.4": [
    {
      "page": "/supply-chain/dependency-awareness",
      "title": "Dependency Awareness",
      "header": "Best Practices for Dependency Awareness",
      "coverage": "partial"
    }
  ],
  "di-3.1.1": [
    {
      "page": "/devsecops/continuous-integration-continuous-deployment",
      "title": "Securing CI/CD Pipelines | SEAL",
      "header": null,
      "coverage": "partial"
    }
  ],
  "di-3.1.2": [],
  "di-3.1.3": [
    {
      "page": "/devsecops/continuous-integration-continuous-deployment",
      "title": "Securing CI/CD Pipelines | SEAL",
      "header": null,
      "coverage": "partial"
    },
    {
      "page": "/devsecops/security-testing",
      "title": "Security Testing",
      "header": null,
      "coverage": "partial"
    }
  ],
  "di-4.1.1": [
    {
      "page": "/security-automation/infrastructure-as-code",
      "title": "Infrastructure as Code Security | SEAL",
      "header": null,
      "coverage": "partial"
    }
  ],
  "di-4.1.2": [
    {
      "page": "/secure-software-development/secure-code-repositories-version-control",
      "title": "Secure Code Repositories & Version Control | SEAL",
      "header": "Best Practices for Secure Code Repositories",
      "coverage": "partial"
    }
  ],
  "di-4.1.3": [
    {
      "page": "/secure-software-development/secure-code-repositories-version-control",
      "title": "Secure Code Repositories & Version Control | SEAL",
      "header": "Secure Version Control Practices",
      "coverage": "partial"
    }
  ],
  "di-4.1.4": [
    {
      "page": "/infrastructure/cloud",
      "title": "Cloud Infrastructure",
      "header": "Cloud Infrastructure",
      "coverage": "partial"
    }
  ],
  "dns-1.1.1": [],
  "dns-1.1.2": [],
  "dns-2.1.1": [],
  "dns-2.1.2": [
    {
      "page": "/infrastructure/domain-and-dns-security/registrar-and-locks",
      "title": "Registrar Security & Registry Locks | SEAL",
      "header": "Choosing a Secure Registrar",
      "coverage": "full"
    }
  ],
  "dns-3.1.1": [
    {
      "page": "/infrastructure/domain-and-dns-security/registrar-and-locks",
      "title": "Registrar Security & Registry Locks | SEAL",
      "header": "Access Control Best Practices",
      "coverage": "partial"
    }
  ],
  "dns-3.1.2": [
    {
      "page": "/infrastructure/domain-and-dns-security/registrar-and-locks",
      "title": "Registrar Security & Registry Locks | SEAL",
      "header": "Dedicated Security Contact Email",
      "coverage": "partial"
    }
  ],
  "dns-3.1.3": [],
  "dns-4.1.1": [
    {
      "page": "/infrastructure/domain-and-dns-security/dnssec-and-email",
      "title": "DNSSEC, CAA, SMTP DANE and Email Security | SEAL",
      "header": "DNSSEC Implementation",
      "coverage": "partial"
    }
  ],
  "dns-4.1.2": [
    {
      "page": "/infrastructure/domain-and-dns-security/dnssec-and-email",
      "title": "DNSSEC, CAA, SMTP DANE and Email Security | SEAL",
      "header": "Email Security Configuration",
      "coverage": "partial"
    }
  ],
  "dns-4.1.3": [
    {
      "page": "/infrastructure/domain-and-dns-security/registrar-and-locks",
      "title": "Registrar Security & Registry Locks | SEAL",
      "header": "Registry Lock (EPP Lock)",
      "coverage": "full"
    }
  ],
  "dns-4.1.4": [],
  "dns-5.1.1": [
    {
      "page": "/infrastructure/domain-and-dns-security/monitoring-and-alerting",
      "title": "DNS Monitoring & Incident Response | SEAL",
      "header": "DNS Record Monitoring",
      "coverage": "partial"
    }
  ],
  "dns-5.1.2": [
    {
      "page": "/infrastructure/domain-and-dns-security/monitoring-and-alerting",
      "title": "DNS Monitoring & Incident Response | SEAL",
      "header": "Certificate Transparency Monitoring",
      "coverage": "full"
    }
  ],
  "dns-5.1.3": [
    {
      "page": "/infrastructure/domain-and-dns-security/registrar-and-locks",
      "title": "Registrar Security & Registry Locks | SEAL",
      "header": "Domain Expiration Protection",
      "coverage": "full"
    }
  ],
  "dns-6.1.1": [
    {
      "page": "/infrastructure/domain-and-dns-security/monitoring-and-alerting",
      "title": "DNS Monitoring & Incident Response | SEAL",
      "header": "Setting Up Alerts",
      "coverage": "partial"
    }
  ],
  "dns-6.1.2": [
    {
      "page": "/infrastructure/domain-and-dns-security/monitoring-and-alerting",
      "title": "DNS Monitoring & Incident Response | SEAL",
      "header": "Incident Response Plan",
      "coverage": "partial"
    }
  ],
  "ir-1.1.1": [],
  "ir-1.1.2": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Contact Information",
      "coverage": "partial"
    },
    {
      "page": "/incident-management/playbooks/seal-911-war-room-guidelines",
      "title": "SEAL 911 War Room Guidelines | SEAL",
      "header": "Key Roles",
      "coverage": "partial"
    },
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Communication & Documentation",
      "coverage": "partial"
    }
  ],
  "ir-2.1.1": [
    {
      "page": "/infrastructure/domain-and-dns-security/monitoring-and-alerting",
      "title": "DNS Monitoring & Incident Response | SEAL",
      "header": "DNS Record Monitoring",
      "coverage": "partial"
    },
    {
      "page": "/monitoring/guidelines",
      "title": "On-Chain Monitoring Guidelines",
      "header": "Best Practices",
      "coverage": "partial"
    }
  ],
  "ir-2.1.2": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Immediate Actions",
      "coverage": "partial"
    }
  ],
  "ir-2.1.3": [],
  "ir-3.1.1": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Key Compromise",
      "coverage": "partial"
    },
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Signer rotation",
      "coverage": "partial"
    }
  ],
  "ir-3.1.2": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Training & Drills",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/setup-and-configuration",
      "title": "Multisig Setup & Configuration | SEAL",
      "header": null,
      "coverage": "partial"
    }
  ],
  "ir-3.1.3": [
    {
      "page": "/multisig-for-protocols/backup-signing-and-infrastructure",
      "title": "Backup Signing & Infrastructure | SEAL",
      "header": "UI Alternatives",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Emergency Preparedness",
      "coverage": "partial"
    }
  ],
  "ir-4.1.1": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Communication Protocols",
      "coverage": "partial"
    }
  ],
  "ir-4.1.2": [
    {
      "page": "/incident-management/communication-strategies",
      "title": "Incident Communication Strategies | SEAL",
      "header": "Best Practices",
      "coverage": "partial"
    }
  ],
  "ir-4.1.3": [
    {
      "page": "/incident-management/playbooks/seal-911-war-room-guidelines",
      "title": "SEAL 911 War Room Guidelines | SEAL",
      "header": "Communications",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Notification Template",
      "coverage": "partial"
    }
  ],
  "ir-5.1.1": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Drill Procedures",
      "coverage": "partial"
    },
    {
      "page": "/incident-management/playbooks/decentralized-ir",
      "title": "Decentralized Incident Response | SEAL",
      "header": "Keep It Alive",
      "coverage": "partial"
    }
  ],
  "ms-1.1.1": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "For Multisig Administrators",
      "coverage": "partial"
    }
  ],
  "ms-1.1.2": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Communication & Documentation",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Documentation & Communication",
      "coverage": "partial"
    }
  ],
  "ms-2.1.1": [
    {
      "page": "/multisig-for-protocols/planning-and-classification",
      "title": "Multisig Planning & Classification | SEAL",
      "header": "Classification Process",
      "coverage": "full"
    },
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Thresholds & Configuration",
      "coverage": "full"
    }
  ],
  "ms-2.1.2": [
    {
      "page": "/multisig-for-protocols/setup-and-configuration",
      "title": "Multisig Setup & Configuration | SEAL",
      "header": "Contract-Level Controls",
      "coverage": "partial"
    },
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Contract-Level Security",
      "coverage": "partial"
    }
  ],
  "ms-2.1.3": [],
  "ms-2.1.4": [],
  "ms-3.1.1": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Communication & Documentation",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/setup-and-configuration",
      "title": "Multisig Setup & Configuration | SEAL",
      "header": "Pre-Launch Checklist",
      "coverage": "partial"
    }
  ],
  "ms-3.1.2": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Thresholds & Configuration",
      "coverage": "full"
    }
  ],
  "ms-3.1.3": [
    {
      "page": "/wallet-security/seed-phrase-management",
      "title": "Seed Phrase Management",
      "header": "Secure Storage Practices",
      "coverage": "full"
    }
  ],
  "ms-3.1.4": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Signer rotation",
      "coverage": "partial"
    }
  ],
  "ms-3.1.5": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "For Signers",
      "coverage": "full"
    }
  ],
  "ms-3.1.6": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Hardware & Security Setup",
      "coverage": "full"
    }
  ],
  "ms-3.1.7": [
    {
      "page": "/multisig-for-protocols/personal-security-opsec",
      "title": "Multisig Personal Security (OpSec) | SEAL",
      "header": "Network Security",
      "coverage": "full"
    }
  ],
  "ms-3.1.8": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Strategic Signer Distribution",
      "coverage": "full"
    }
  ],
  "ms-4.1.1": [
    {
      "page": "/wallet-security/signing-and-verification/secure-multisig-signing-process",
      "title": "Secure Multisig Signing Process | SEAL",
      "header": "Phase 1: Signing the Off-Chain Message",
      "coverage": "full"
    },
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Operational Best Practices",
      "coverage": "partial"
    }
  ],
  "ms-4.1.2": [],
  "ms-4.1.3": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Transaction Verification",
      "coverage": "partial"
    }
  ],
  "ms-4.1.4": [
    {
      "page": "/multisig-for-protocols/backup-signing-and-infrastructure",
      "title": "Backup Signing & Infrastructure | SEAL",
      "header": "UI Alternatives",
      "coverage": "full"
    }
  ],
  "ms-5.1.1": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Communication Account Compromise",
      "coverage": "partial"
    }
  ],
  "ms-5.1.2": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Contact Information",
      "coverage": "partial"
    }
  ],
  "ms-6.1.1": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Key Compromise",
      "coverage": "full"
    }
  ],
  "ms-6.1.2": [
    {
      "page": "/multisig-for-protocols/planning-and-classification",
      "title": "Multisig Planning & Classification | SEAL",
      "header": "Step 2: Operational Assessment",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "For Emergency Response Multisigs",
      "coverage": "partial"
    }
  ],
  "ms-6.1.3": [
    {
      "page": "/wallet-security/secure-multisig-best-practices",
      "title": "Secure Multisig Best Practices | SEAL",
      "header": "Operational Best Practices",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/setup-and-configuration",
      "title": "Multisig Setup & Configuration | SEAL",
      "header": "Active Monitoring",
      "coverage": "partial"
    }
  ],
  "ms-6.1.4": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Specialized Training by Use Case",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Drill Procedures",
      "coverage": "full"
    }
  ],
  "tro-1.1.1": [],
  "tro-1.1.2": [
    {
      "page": "/treasury-operations/registration-documents",
      "title": "Custodial Account Registration | SEAL",
      "header": "Registration Template",
      "coverage": "partial"
    }
  ],
  "tro-1.1.3": [
    {
      "page": "/treasury-operations/enhanced-controls",
      "title": "Enhanced Controls for High-Risk Accounts | SEAL",
      "header": "MPC for Large Holdings",
      "coverage": "partial"
    }
  ],
  "tro-1.1.4": [
    {
      "page": "/treasury-operations/registration-documents",
      "title": "Custodial Account Registration | SEAL",
      "header": "Access Change Template",
      "coverage": "partial"
    }
  ],
  "tro-2.1.1": [
    {
      "page": "/treasury-operations/classification",
      "title": "Treasury Security Classification | SEAL",
      "header": null,
      "coverage": "full"
    }
  ],
  "tro-2.1.2": [],
  "tro-3.1.1": [
    {
      "page": "/treasury-operations/enhanced-controls",
      "title": "Enhanced Controls for High-Risk Accounts | SEAL",
      "header": "Access Security",
      "coverage": "partial"
    },
    {
      "page": "/treasury-operations/registration-documents",
      "title": "Custodial Account Registration | SEAL",
      "header": "Security Configuration Template",
      "coverage": "partial"
    }
  ],
  "tro-3.1.2": [
    {
      "page": "/treasury-operations/enhanced-controls",
      "title": "Enhanced Controls for High-Risk Accounts | SEAL",
      "header": "Access Security",
      "coverage": "partial"
    },
    {
      "page": "/wallet-security/seed-phrase-management",
      "title": "Seed Phrase Management",
      "header": null,
      "coverage": "partial"
    }
  ],
  "tro-3.1.3": [
    {
      "page": "/treasury-operations/registration-documents",
      "title": "Custodial Account Registration | SEAL",
      "header": "Quarterly Review Template",
      "coverage": "full"
    }
  ],
  "tro-3.1.4": [
    {
      "page": "/treasury-operations/enhanced-controls",
      "title": "Enhanced Controls for High-Risk Accounts | SEAL",
      "header": "Device Security",
      "coverage": "partial"
    },
    {
      "page": "/wallet-security/seed-phrase-management",
      "title": "Seed Phrase Management",
      "header": "Secure Storage Practices",
      "coverage": "partial"
    },
    {
      "page": "/multisig-for-protocols/personal-security-opsec",
      "title": "Multisig Personal Security (OpSec) | SEAL",
      "header": "Device Security",
      "coverage": "partial"
    }
  ],
  "tro-4.1.1": [
    {
      "page": "/treasury-operations/transaction-verification",
      "title": "Treasury Transaction Verification | SEAL",
      "header": "Execution Protocol",
      "coverage": "partial"
    }
  ],
  "tro-4.1.2": [
    {
      "page": "/multisig-for-protocols/implementation-checklist",
      "title": "Multisig Implementation Checklist | SEAL",
      "header": "Transaction Verification",
      "coverage": "partial"
    }
  ],
  "tro-4.1.3": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Communication Account Compromise",
      "coverage": "partial"
    }
  ],
  "tro-5.1.1": [],
  "tro-5.1.2": [
    {
      "page": "/treasury-operations/transaction-verification",
      "title": "Treasury Transaction Verification | SEAL",
      "header": "Transaction Parameter Security",
      "coverage": "partial"
    }
  ],
  "tro-6.1.1": [
    {
      "page": "/treasury-operations/enhanced-controls",
      "title": "Enhanced Controls for High-Risk Accounts | SEAL",
      "header": "Security Monitoring & Logging",
      "coverage": "partial"
    }
  ],
  "tro-6.1.2": [
    {
      "page": "/multisig-for-protocols/emergency-procedures",
      "title": "Multisig Emergency Procedures | SEAL",
      "header": "Emergency Notification Template",
      "coverage": "full"
    }
  ],
  "tro-7.1.1": [],
  "tro-7.1.2": [
    {
      "page": "/multisig-for-protocols/backup-signing-and-infrastructure",
      "title": "Backup Signing & Infrastructure | SEAL",
      "header": "UI Alternatives",
      "coverage": "full"
    }
  ],
  "tro-8.1.1": [
    {
      "page": "/treasury-operations/registration-documents",
      "title": "Custodial Account Registration | SEAL",
      "header": "Security Configuration Template",
      "coverage": "partial"
    }
  ],
  "tro-8.1.2": [],
  "ws-1.1.1": [
    {
      "page": "/opsec/core-concepts/security-fundamentals",
      "title": "Security Fundamentals",
      "header": "Continuous Visibility",
      "coverage": "partial"
    }
  ],
  "ws-1.1.2": [],
  "ws-1.1.3": [
    {
      "page": "/opsec/core-concepts/implementation-process",
      "title": "OpSec Implementation Process | SEAL",
      "header": "Critical Asset Identification",
      "coverage": "partial"
    }
  ],
  "ws-1.1.4": [
    {
      "page": "/opsec/core-concepts/security-fundamentals",
      "title": "Security Fundamentals",
      "header": "Information Flow Control",
      "coverage": "full"
    },
    {
      "page": "/opsec/core-concepts/implementation-process",
      "title": "OpSec Implementation Process | SEAL",
      "header": "Critical Asset Identification",
      "coverage": "full"
    }
  ],
  "ws-2.1.1": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Secure devices with encryption & updates",
      "coverage": "partial"
    },
    {
      "page": "/encryption/volume-encryption",
      "title": "Volume Encryption",
      "header": null,
      "coverage": "partial"
    },
    {
      "page": "/encryption/partition-encryption",
      "title": "Partition Encryption",
      "header": null,
      "coverage": "partial"
    }
  ],
  "ws-2.1.2": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Back up and prepare for loss",
      "coverage": "partial"
    },
    {
      "page": "/opsec/control-domains/physical-environmental",
      "title": "Physical & Environmental Security",
      "header": "Physical Security of Critical Assets",
      "coverage": "partial"
    }
  ],
  "ws-2.1.3": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Inspect and clean your devices",
      "coverage": "partial"
    }
  ],
  "ws-2.1.4": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": null,
      "coverage": "full"
    },
    {
      "page": "/opsec/control-domains/physical-environmental",
      "title": "Physical & Environmental Security",
      "header": "Secure Workspace & Travel Security",
      "coverage": "full"
    }
  ],
  "ws-3.1.1": [
    {
      "page": "/guides/account_management/discord",
      "title": "Discord Security",
      "header": "Roles",
      "coverage": "partial"
    }
  ],
  "ws-3.1.2": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Protect Accounts with 2FA redundancy",
      "coverage": "partial"
    },
    {
      "page": "/opsec/control-domains/technical",
      "title": "Technical Security Controls",
      "header": "Two-Factor & Hardware Authentication",
      "coverage": "partial"
    },
    {
      "page": "/guides/account_management/discord",
      "title": "Discord Security",
      "header": "For Individuals - Account Security Checklist",
      "coverage": "partial"
    }
  ],
  "ws-3.1.3": [
    {
      "page": "/guides/account_management/discord",
      "title": "Discord Security",
      "header": "Server Settings Checklist",
      "coverage": "partial"
    }
  ],
  "ws-3.1.4": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Protect Accounts with 2FA redundancy",
      "coverage": "partial"
    },
    {
      "page": "/awareness/cultivating-a-security-aware-mindset",
      "title": "Cultivating A Security Aware Mindset | SEAL",
      "header": "Password Management",
      "coverage": "partial"
    },
    {
      "page": "/guides/account_management/telegram",
      "title": "Telegram Security",
      "header": "Account Security Checklist",
      "coverage": "partial"
    }
  ],
  "ws-3.1.5": [
    {
      "page": "/opsec/core-concepts/security-fundamentals",
      "title": "Security Fundamentals",
      "header": "Minimal Access Scopes",
      "coverage": "partial"
    },
    {
      "page": "/guides/account_management/discord",
      "title": "Discord Security",
      "header": "Regular Reviews",
      "coverage": "partial"
    }
  ],
  "ws-4.1.1": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Minimize digital footprint & social visibility",
      "coverage": "partial"
    }
  ],
  "ws-4.1.2": [
    {
      "page": "/guides/account_management/github",
      "title": "GitHub Security",
      "header": "Repository Settings",
      "coverage": "full"
    }
  ],
  "ws-5.1.1": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Network safety – avoid untrusted Wi-Fi & Bluetooth",
      "coverage": "partial"
    },
    {
      "page": "/opsec/control-domains/technical",
      "title": "Technical Security Controls",
      "header": "Network & Communication Security",
      "coverage": "partial"
    }
  ],
  "ws-5.1.2": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Plan emergency and incident responses",
      "coverage": "partial"
    },
    {
      "page": "/guides/account_management/telegram",
      "title": "Telegram Security",
      "header": "Use Secret Chats for Enhanced Privacy",
      "coverage": "partial"
    },
    {
      "page": "/opsec/control-domains/technical",
      "title": "Technical Security Controls",
      "header": "Network & Communication Security",
      "coverage": "partial"
    }
  ],
  "ws-6.1.1": [
    {
      "page": "/opsec/control-domains/people",
      "title": "Personnel Security Controls",
      "header": "Personnel Security Measures",
      "coverage": "partial"
    }
  ],
  "ws-6.1.2": [
    {
      "page": "/opsec/travel/guide",
      "title": "Travel Security Guide",
      "header": "Back up and prepare for loss",
      "coverage": "partial"
    },
    {
      "page": "/awareness/understanding-threat-vectors",
      "title": "Understanding Threat Vectors",
      "header": null,
      "coverage": "partial"
    },
    {
      "page": "/guides/account_management/discord",
      "title": "Discord Security",
      "header": "Regular Reviews",
      "coverage": "partial"
    }
  ],
  "ws-6.1.3": [
    {
      "page": "/awareness/staying-informed-and-continuous-learning",
      "title": "Staying Informed And Continuous Learning | SEAL",
      "header": "Comprehensive Security Training Framework",
      "coverage": "partial"
    },
    {
      "page": "/opsec/control-domains/people",
      "title": "Personnel Security Controls",
      "header": "Security Training & Culture",
      "coverage": "partial"
    },
    {
      "page": "/opsec/appendices/case-studies",
      "title": "OpSec Case Studies",
      "header": null,
      "coverage": "partial"
    }
  ],
  "ws-7.1.1": [
    {
      "page": "/opsec/core-concepts/security-fundamentals",
      "title": "Security Fundamentals",
      "header": "Continuous Visibility",
      "coverage": "partial"
    },
    {
      "page": "/opsec/appendices/case-studies",
      "title": "OpSec Case Studies",
      "header": "Tabletop Exercises",
      "coverage": "partial"
    }
  ],
  "ws-7.1.2": [
    {
      "page": "/opsec/core-concepts/security-fundamentals",
      "title": "Security Fundamentals",
      "header": "Minimal Access Scopes",
      "coverage": "partial"
    },
    {
      "page": "/opsec/control-domains/people",
      "title": "Personnel Security Controls",
      "header": "Insider-Threat Mitigation",
      "coverage": "partial"
    }
  ],
  "ws-7.1.3": [
    {
      "page": "/opsec/core-concepts/security-fundamentals",
      "title": "Security Fundamentals",
      "header": "Minimal Access Scopes",
      "coverage": "partial"
    },
    {
      "page": "/guides/account_management/discord",
      "title": "Discord Security",
      "header": "Integrations",
      "coverage": "partial"
    }
  ]
};

/** Reverse index: framework page path → cert controls that reference it */
export const frameworkToControls: Record<string, CertRef[]> = {
  "/devsecops/integrated-development-environments": [
    {
      "controlId": "di-1.1.3",
      "controlTitle": "Development Environment Isolation",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    },
    {
      "controlId": "di-1.1.4",
      "controlTitle": "Development Tools Approval",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/secure-software-development/secure-code-repositories-version-control": [
    {
      "controlId": "di-2.1.1",
      "controlTitle": "Repository Security",
      "certName": "sfc-devops-infrastructure",
      "header": "Best Practices for Secure Code Repositories",
      "coverage": "partial"
    },
    {
      "controlId": "di-4.1.2",
      "controlTitle": "Infrastructure Access Controls",
      "certName": "sfc-devops-infrastructure",
      "header": "Best Practices for Secure Code Repositories",
      "coverage": "partial"
    },
    {
      "controlId": "di-4.1.3",
      "controlTitle": "Backup and Disaster Recovery",
      "certName": "sfc-devops-infrastructure",
      "header": "Secure Version Control Practices",
      "coverage": "partial"
    }
  ],
  "/devsecops/continuous-integration-continuous-deployment": [
    {
      "controlId": "di-2.1.2",
      "controlTitle": "Secret Scanning",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    },
    {
      "controlId": "di-3.1.1",
      "controlTitle": "Pipeline Security Controls",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    },
    {
      "controlId": "di-3.1.3",
      "controlTitle": "Security Testing Integration",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/supply-chain/dependency-awareness": [
    {
      "controlId": "di-2.1.4",
      "controlTitle": "Dependency and Supply Chain Security",
      "certName": "sfc-devops-infrastructure",
      "header": "Best Practices for Dependency Awareness",
      "coverage": "partial"
    }
  ],
  "/devsecops/security-testing": [
    {
      "controlId": "di-3.1.3",
      "controlTitle": "Security Testing Integration",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/security-automation/infrastructure-as-code": [
    {
      "controlId": "di-4.1.1",
      "controlTitle": "Infrastructure as Code",
      "certName": "sfc-devops-infrastructure",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/infrastructure/cloud": [
    {
      "controlId": "di-4.1.4",
      "controlTitle": "Cloud Security Monitoring",
      "certName": "sfc-devops-infrastructure",
      "header": "Cloud Infrastructure",
      "coverage": "partial"
    }
  ],
  "/infrastructure/domain-and-dns-security/registrar-and-locks": [
    {
      "controlId": "dns-2.1.2",
      "controlTitle": "Enterprise Registrar Security Requirements",
      "certName": "sfc-dns-registrar",
      "header": "Choosing a Secure Registrar",
      "coverage": "full"
    },
    {
      "controlId": "dns-3.1.1",
      "controlTitle": "Registrar Access Control",
      "certName": "sfc-dns-registrar",
      "header": "Access Control Best Practices",
      "coverage": "partial"
    },
    {
      "controlId": "dns-3.1.2",
      "controlTitle": "Dedicated Domain Security Contact Email",
      "certName": "sfc-dns-registrar",
      "header": "Dedicated Security Contact Email",
      "coverage": "partial"
    },
    {
      "controlId": "dns-4.1.3",
      "controlTitle": "Domain Lock Implementation",
      "certName": "sfc-dns-registrar",
      "header": "Registry Lock (EPP Lock)",
      "coverage": "full"
    },
    {
      "controlId": "dns-5.1.3",
      "controlTitle": "Domain Expiration Prevention",
      "certName": "sfc-dns-registrar",
      "header": "Domain Expiration Protection",
      "coverage": "full"
    }
  ],
  "/infrastructure/domain-and-dns-security/dnssec-and-email": [
    {
      "controlId": "dns-4.1.1",
      "controlTitle": "DNS Security Standards",
      "certName": "sfc-dns-registrar",
      "header": "DNSSEC Implementation",
      "coverage": "partial"
    },
    {
      "controlId": "dns-4.1.2",
      "controlTitle": "Email Authentication Standards",
      "certName": "sfc-dns-registrar",
      "header": "Email Security Configuration",
      "coverage": "partial"
    }
  ],
  "/infrastructure/domain-and-dns-security/monitoring-and-alerting": [
    {
      "controlId": "dns-5.1.1",
      "controlTitle": "Domain and DNS Monitoring",
      "certName": "sfc-dns-registrar",
      "header": "DNS Record Monitoring",
      "coverage": "partial"
    },
    {
      "controlId": "dns-5.1.2",
      "controlTitle": "Certificate Transparency Monitoring",
      "certName": "sfc-dns-registrar",
      "header": "Certificate Transparency Monitoring",
      "coverage": "full"
    },
    {
      "controlId": "dns-6.1.1",
      "controlTitle": "Alerting and Emergency Contacts",
      "certName": "sfc-dns-registrar",
      "header": "Setting Up Alerts",
      "coverage": "partial"
    },
    {
      "controlId": "dns-6.1.2",
      "controlTitle": "Domain Incident Response Plan",
      "certName": "sfc-dns-registrar",
      "header": "Incident Response Plan",
      "coverage": "partial"
    },
    {
      "controlId": "ir-2.1.1",
      "controlTitle": "Monitoring Coverage",
      "certName": "sfc-incident-response",
      "header": "DNS Record Monitoring",
      "coverage": "partial"
    }
  ],
  "/multisig-for-protocols/emergency-procedures": [
    {
      "controlId": "ir-1.1.2",
      "controlTitle": "Stakeholder Coordination and Contacts",
      "certName": "sfc-incident-response",
      "header": "Emergency Contact Information",
      "coverage": "partial"
    },
    {
      "controlId": "ir-2.1.2",
      "controlTitle": "Alerting, Paging, and Escalation",
      "certName": "sfc-incident-response",
      "header": "Immediate Actions",
      "coverage": "partial"
    },
    {
      "controlId": "ir-3.1.1",
      "controlTitle": "Response Playbooks",
      "certName": "sfc-incident-response",
      "header": "Key Compromise",
      "coverage": "partial"
    },
    {
      "controlId": "ir-4.1.1",
      "controlTitle": "Incident Communication Channels",
      "certName": "sfc-incident-response",
      "header": "Emergency Communication Protocols",
      "coverage": "partial"
    },
    {
      "controlId": "ir-4.1.3",
      "controlTitle": "Public Communication and Information Management",
      "certName": "sfc-incident-response",
      "header": "Emergency Notification Template",
      "coverage": "partial"
    },
    {
      "controlId": "ir-5.1.1",
      "controlTitle": "IR Drills and Testing",
      "certName": "sfc-incident-response",
      "header": "Emergency Drill Procedures",
      "coverage": "partial"
    },
    {
      "controlId": "ms-5.1.1",
      "controlTitle": "Secure Communication Procedures",
      "certName": "sfc-multisig-ops",
      "header": "Communication Account Compromise",
      "coverage": "partial"
    },
    {
      "controlId": "ms-5.1.2",
      "controlTitle": "Emergency Contact List",
      "certName": "sfc-multisig-ops",
      "header": "Emergency Contact Information",
      "coverage": "partial"
    },
    {
      "controlId": "ms-6.1.1",
      "controlTitle": "Emergency Playbooks",
      "certName": "sfc-multisig-ops",
      "header": "Key Compromise",
      "coverage": "full"
    },
    {
      "controlId": "ms-6.1.2",
      "controlTitle": "Signer Reachability and Escalation",
      "certName": "sfc-multisig-ops",
      "header": "For Emergency Response Multisigs",
      "coverage": "partial"
    },
    {
      "controlId": "ms-6.1.4",
      "controlTitle": "Emergency Drills and Improvement",
      "certName": "sfc-multisig-ops",
      "header": "Emergency Drill Procedures",
      "coverage": "full"
    },
    {
      "controlId": "tro-4.1.3",
      "controlTitle": "Secure Communication Procedures",
      "certName": "sfc-treasury-ops",
      "header": "Communication Account Compromise",
      "coverage": "partial"
    },
    {
      "controlId": "tro-6.1.2",
      "controlTitle": "Incident Response Plan",
      "certName": "sfc-treasury-ops",
      "header": "Emergency Notification Template",
      "coverage": "full"
    }
  ],
  "/incident-management/playbooks/seal-911-war-room-guidelines": [
    {
      "controlId": "ir-1.1.2",
      "controlTitle": "Stakeholder Coordination and Contacts",
      "certName": "sfc-incident-response",
      "header": "Key Roles",
      "coverage": "partial"
    },
    {
      "controlId": "ir-4.1.3",
      "controlTitle": "Public Communication and Information Management",
      "certName": "sfc-incident-response",
      "header": "Communications",
      "coverage": "partial"
    }
  ],
  "/wallet-security/secure-multisig-best-practices": [
    {
      "controlId": "ir-1.1.2",
      "controlTitle": "Stakeholder Coordination and Contacts",
      "certName": "sfc-incident-response",
      "header": "Communication & Documentation",
      "coverage": "partial"
    },
    {
      "controlId": "ir-3.1.1",
      "controlTitle": "Response Playbooks",
      "certName": "sfc-incident-response",
      "header": "Signer rotation",
      "coverage": "partial"
    },
    {
      "controlId": "ir-3.1.2",
      "controlTitle": "Signer Reachability and Coordination",
      "certName": "sfc-incident-response",
      "header": "Training & Drills",
      "coverage": "partial"
    },
    {
      "controlId": "ms-1.1.2",
      "controlTitle": "Multisig Registry and Documentation",
      "certName": "sfc-multisig-ops",
      "header": "Communication & Documentation",
      "coverage": "partial"
    },
    {
      "controlId": "ms-2.1.1",
      "controlTitle": "Multisig Classification and Risk-Based Controls",
      "certName": "sfc-multisig-ops",
      "header": "Thresholds & Configuration",
      "coverage": "full"
    },
    {
      "controlId": "ms-2.1.2",
      "controlTitle": "Contract-Level Security Controls",
      "certName": "sfc-multisig-ops",
      "header": "Contract-Level Security",
      "coverage": "partial"
    },
    {
      "controlId": "ms-3.1.1",
      "controlTitle": "Signer Address Verification",
      "certName": "sfc-multisig-ops",
      "header": "Communication & Documentation",
      "coverage": "partial"
    },
    {
      "controlId": "ms-3.1.2",
      "controlTitle": "Signer Key Management Standards",
      "certName": "sfc-multisig-ops",
      "header": "Thresholds & Configuration",
      "coverage": "full"
    },
    {
      "controlId": "ms-3.1.4",
      "controlTitle": "Signer Lifecycle Management",
      "certName": "sfc-multisig-ops",
      "header": "Signer rotation",
      "coverage": "partial"
    },
    {
      "controlId": "ms-3.1.8",
      "controlTitle": "Signer Diversity",
      "certName": "sfc-multisig-ops",
      "header": "Strategic Signer Distribution",
      "coverage": "full"
    },
    {
      "controlId": "ms-4.1.1",
      "controlTitle": "Transaction Handling Process",
      "certName": "sfc-multisig-ops",
      "header": "Operational Best Practices",
      "coverage": "partial"
    },
    {
      "controlId": "ms-6.1.3",
      "controlTitle": "Multisig Monitoring and Alerts",
      "certName": "sfc-multisig-ops",
      "header": "Operational Best Practices",
      "coverage": "partial"
    }
  ],
  "/monitoring/guidelines": [
    {
      "controlId": "ir-2.1.1",
      "controlTitle": "Monitoring Coverage",
      "certName": "sfc-incident-response",
      "header": "Best Practices",
      "coverage": "partial"
    }
  ],
  "/multisig-for-protocols/setup-and-configuration": [
    {
      "controlId": "ir-3.1.2",
      "controlTitle": "Signer Reachability and Coordination",
      "certName": "sfc-incident-response",
      "header": null,
      "coverage": "partial"
    },
    {
      "controlId": "ms-2.1.2",
      "controlTitle": "Contract-Level Security Controls",
      "certName": "sfc-multisig-ops",
      "header": "Contract-Level Controls",
      "coverage": "partial"
    },
    {
      "controlId": "ms-3.1.1",
      "controlTitle": "Signer Address Verification",
      "certName": "sfc-multisig-ops",
      "header": "Pre-Launch Checklist",
      "coverage": "partial"
    },
    {
      "controlId": "ms-6.1.3",
      "controlTitle": "Multisig Monitoring and Alerts",
      "certName": "sfc-multisig-ops",
      "header": "Active Monitoring",
      "coverage": "partial"
    }
  ],
  "/multisig-for-protocols/backup-signing-and-infrastructure": [
    {
      "controlId": "ir-3.1.3",
      "controlTitle": "Emergency Transaction Readiness",
      "certName": "sfc-incident-response",
      "header": "UI Alternatives",
      "coverage": "partial"
    },
    {
      "controlId": "ms-4.1.4",
      "controlTitle": "Backup Signing Infrastructure",
      "certName": "sfc-multisig-ops",
      "header": "UI Alternatives",
      "coverage": "full"
    },
    {
      "controlId": "tro-7.1.2",
      "controlTitle": "Backup Infrastructure and Alternate Access",
      "certName": "sfc-treasury-ops",
      "header": "UI Alternatives",
      "coverage": "full"
    }
  ],
  "/multisig-for-protocols/implementation-checklist": [
    {
      "controlId": "ir-3.1.3",
      "controlTitle": "Emergency Transaction Readiness",
      "certName": "sfc-incident-response",
      "header": "Emergency Preparedness",
      "coverage": "partial"
    },
    {
      "controlId": "ir-4.1.1",
      "controlTitle": "Incident Communication Channels",
      "certName": "sfc-incident-response",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "controlId": "ms-1.1.1",
      "controlTitle": "Named Multisig Operations Owner",
      "certName": "sfc-multisig-ops",
      "header": "For Multisig Administrators",
      "coverage": "partial"
    },
    {
      "controlId": "ms-1.1.2",
      "controlTitle": "Multisig Registry and Documentation",
      "certName": "sfc-multisig-ops",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "controlId": "ms-3.1.5",
      "controlTitle": "Signer Training and Assessment",
      "certName": "sfc-multisig-ops",
      "header": "For Signers",
      "coverage": "full"
    },
    {
      "controlId": "ms-3.1.6",
      "controlTitle": "Hardware Wallet Standards",
      "certName": "sfc-multisig-ops",
      "header": "Hardware & Security Setup",
      "coverage": "full"
    },
    {
      "controlId": "ms-4.1.3",
      "controlTitle": "Tool and Platform Evaluation",
      "certName": "sfc-multisig-ops",
      "header": "Transaction Verification",
      "coverage": "partial"
    },
    {
      "controlId": "ms-5.1.1",
      "controlTitle": "Secure Communication Procedures",
      "certName": "sfc-multisig-ops",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "controlId": "ms-5.1.2",
      "controlTitle": "Emergency Contact List",
      "certName": "sfc-multisig-ops",
      "header": "Documentation & Communication",
      "coverage": "partial"
    },
    {
      "controlId": "ms-6.1.4",
      "controlTitle": "Emergency Drills and Improvement",
      "certName": "sfc-multisig-ops",
      "header": "Specialized Training by Use Case",
      "coverage": "partial"
    },
    {
      "controlId": "tro-4.1.2",
      "controlTitle": "Signer and Approver Knowledge",
      "certName": "sfc-treasury-ops",
      "header": "Transaction Verification",
      "coverage": "partial"
    }
  ],
  "/incident-management/communication-strategies": [
    {
      "controlId": "ir-4.1.2",
      "controlTitle": "Internal Status Updates",
      "certName": "sfc-incident-response",
      "header": "Best Practices",
      "coverage": "partial"
    }
  ],
  "/incident-management/playbooks/decentralized-ir": [
    {
      "controlId": "ir-5.1.1",
      "controlTitle": "IR Drills and Testing",
      "certName": "sfc-incident-response",
      "header": "Keep It Alive",
      "coverage": "partial"
    }
  ],
  "/multisig-for-protocols/planning-and-classification": [
    {
      "controlId": "ms-2.1.1",
      "controlTitle": "Multisig Classification and Risk-Based Controls",
      "certName": "sfc-multisig-ops",
      "header": "Classification Process",
      "coverage": "full"
    },
    {
      "controlId": "ms-6.1.2",
      "controlTitle": "Signer Reachability and Escalation",
      "certName": "sfc-multisig-ops",
      "header": "Step 2: Operational Assessment",
      "coverage": "partial"
    }
  ],
  "/wallet-security/seed-phrase-management": [
    {
      "controlId": "ms-3.1.3",
      "controlTitle": "Seed Phrase Backup and Protection",
      "certName": "sfc-multisig-ops",
      "header": "Secure Storage Practices",
      "coverage": "full"
    },
    {
      "controlId": "tro-3.1.2",
      "controlTitle": "Credential and Secret Management",
      "certName": "sfc-treasury-ops",
      "header": null,
      "coverage": "partial"
    },
    {
      "controlId": "tro-3.1.4",
      "controlTitle": "Personnel Operational Security",
      "certName": "sfc-treasury-ops",
      "header": "Secure Storage Practices",
      "coverage": "partial"
    }
  ],
  "/multisig-for-protocols/personal-security-opsec": [
    {
      "controlId": "ms-3.1.7",
      "controlTitle": "Secure Signing Environment",
      "certName": "sfc-multisig-ops",
      "header": "Network Security",
      "coverage": "full"
    },
    {
      "controlId": "tro-3.1.4",
      "controlTitle": "Personnel Operational Security",
      "certName": "sfc-treasury-ops",
      "header": "Device Security",
      "coverage": "partial"
    }
  ],
  "/wallet-security/signing-and-verification/secure-multisig-signing-process": [
    {
      "controlId": "ms-4.1.1",
      "controlTitle": "Transaction Handling Process",
      "certName": "sfc-multisig-ops",
      "header": "Phase 1: Signing the Off-Chain Message",
      "coverage": "full"
    }
  ],
  "/treasury-operations/registration-documents": [
    {
      "controlId": "tro-1.1.2",
      "controlTitle": "Treasury Registry and Documentation",
      "certName": "sfc-treasury-ops",
      "header": "Registration Template",
      "coverage": "partial"
    },
    {
      "controlId": "tro-1.1.4",
      "controlTitle": "Treasury Infrastructure Change Management",
      "certName": "sfc-treasury-ops",
      "header": "Access Change Template",
      "coverage": "partial"
    },
    {
      "controlId": "tro-3.1.1",
      "controlTitle": "Custody Platform Security Configuration",
      "certName": "sfc-treasury-ops",
      "header": "Security Configuration Template",
      "coverage": "partial"
    },
    {
      "controlId": "tro-3.1.3",
      "controlTitle": "Access Reviews for Treasury Systems",
      "certName": "sfc-treasury-ops",
      "header": "Quarterly Review Template",
      "coverage": "full"
    },
    {
      "controlId": "tro-8.1.1",
      "controlTitle": "Financial Recordkeeping and Reconciliation",
      "certName": "sfc-treasury-ops",
      "header": "Security Configuration Template",
      "coverage": "partial"
    }
  ],
  "/treasury-operations/enhanced-controls": [
    {
      "controlId": "tro-1.1.3",
      "controlTitle": "Custody Architecture Rationale",
      "certName": "sfc-treasury-ops",
      "header": "MPC for Large Holdings",
      "coverage": "partial"
    },
    {
      "controlId": "tro-3.1.1",
      "controlTitle": "Custody Platform Security Configuration",
      "certName": "sfc-treasury-ops",
      "header": "Access Security",
      "coverage": "partial"
    },
    {
      "controlId": "tro-3.1.2",
      "controlTitle": "Credential and Secret Management",
      "certName": "sfc-treasury-ops",
      "header": "Access Security",
      "coverage": "partial"
    },
    {
      "controlId": "tro-3.1.4",
      "controlTitle": "Personnel Operational Security",
      "certName": "sfc-treasury-ops",
      "header": "Device Security",
      "coverage": "partial"
    },
    {
      "controlId": "tro-6.1.1",
      "controlTitle": "Monitoring and Threat Awareness",
      "certName": "sfc-treasury-ops",
      "header": "Security Monitoring & Logging",
      "coverage": "partial"
    }
  ],
  "/treasury-operations/classification": [
    {
      "controlId": "tro-2.1.1",
      "controlTitle": "Treasury Wallet Risk Classification",
      "certName": "sfc-treasury-ops",
      "header": null,
      "coverage": "full"
    }
  ],
  "/treasury-operations/transaction-verification": [
    {
      "controlId": "tro-4.1.1",
      "controlTitle": "Transaction Verification and Execution",
      "certName": "sfc-treasury-ops",
      "header": "Execution Protocol",
      "coverage": "partial"
    },
    {
      "controlId": "tro-5.1.2",
      "controlTitle": "Position Lifecycle Management",
      "certName": "sfc-treasury-ops",
      "header": "Transaction Parameter Security",
      "coverage": "partial"
    }
  ],
  "/opsec/core-concepts/security-fundamentals": [
    {
      "controlId": "ws-1.1.1",
      "controlTitle": "Workspace Security Owner",
      "certName": "sfc-workspace-security",
      "header": "Continuous Visibility",
      "coverage": "partial"
    },
    {
      "controlId": "ws-1.1.4",
      "controlTitle": "System and Data Classification",
      "certName": "sfc-workspace-security",
      "header": "Information Flow Control",
      "coverage": "full"
    },
    {
      "controlId": "ws-3.1.5",
      "controlTitle": "Access Reviews",
      "certName": "sfc-workspace-security",
      "header": "Minimal Access Scopes",
      "coverage": "partial"
    },
    {
      "controlId": "ws-7.1.1",
      "controlTitle": "Workspace Security Monitoring and Incident Response",
      "certName": "sfc-workspace-security",
      "header": "Continuous Visibility",
      "coverage": "partial"
    },
    {
      "controlId": "ws-7.1.2",
      "controlTitle": "Insider Threat Assessment",
      "certName": "sfc-workspace-security",
      "header": "Minimal Access Scopes",
      "coverage": "partial"
    },
    {
      "controlId": "ws-7.1.3",
      "controlTitle": "Third-Party Access Management",
      "certName": "sfc-workspace-security",
      "header": "Minimal Access Scopes",
      "coverage": "partial"
    }
  ],
  "/opsec/core-concepts/implementation-process": [
    {
      "controlId": "ws-1.1.3",
      "controlTitle": "Asset Inventory",
      "certName": "sfc-workspace-security",
      "header": "Critical Asset Identification",
      "coverage": "partial"
    },
    {
      "controlId": "ws-1.1.4",
      "controlTitle": "System and Data Classification",
      "certName": "sfc-workspace-security",
      "header": "Critical Asset Identification",
      "coverage": "full"
    }
  ],
  "/opsec/travel/guide": [
    {
      "controlId": "ws-2.1.1",
      "controlTitle": "Device Security Standards",
      "certName": "sfc-workspace-security",
      "header": "Secure devices with encryption & updates",
      "coverage": "partial"
    },
    {
      "controlId": "ws-2.1.2",
      "controlTitle": "Device Lifecycle Management",
      "certName": "sfc-workspace-security",
      "header": "Back up and prepare for loss",
      "coverage": "partial"
    },
    {
      "controlId": "ws-2.1.3",
      "controlTitle": "Endpoint Protection",
      "certName": "sfc-workspace-security",
      "header": "Inspect and clean your devices",
      "coverage": "partial"
    },
    {
      "controlId": "ws-2.1.4",
      "controlTitle": "Physical and Travel Security",
      "certName": "sfc-workspace-security",
      "header": null,
      "coverage": "full"
    },
    {
      "controlId": "ws-3.1.2",
      "controlTitle": "Multi-Factor Authentication",
      "certName": "sfc-workspace-security",
      "header": "Protect Accounts with 2FA redundancy",
      "coverage": "partial"
    },
    {
      "controlId": "ws-3.1.4",
      "controlTitle": "Credential Management Standards",
      "certName": "sfc-workspace-security",
      "header": "Protect Accounts with 2FA redundancy",
      "coverage": "partial"
    },
    {
      "controlId": "ws-4.1.1",
      "controlTitle": "Software Evaluation and Approval",
      "certName": "sfc-workspace-security",
      "header": "Minimize digital footprint & social visibility",
      "coverage": "partial"
    },
    {
      "controlId": "ws-5.1.1",
      "controlTitle": "Network Security",
      "certName": "sfc-workspace-security",
      "header": "Network safety – avoid untrusted Wi-Fi & Bluetooth",
      "coverage": "partial"
    },
    {
      "controlId": "ws-5.1.2",
      "controlTitle": "Secure Communications",
      "certName": "sfc-workspace-security",
      "header": "Plan emergency and incident responses",
      "coverage": "partial"
    },
    {
      "controlId": "ws-6.1.2",
      "controlTitle": "Security Offboarding",
      "certName": "sfc-workspace-security",
      "header": "Back up and prepare for loss",
      "coverage": "partial"
    }
  ],
  "/encryption/volume-encryption": [
    {
      "controlId": "ws-2.1.1",
      "controlTitle": "Device Security Standards",
      "certName": "sfc-workspace-security",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/encryption/partition-encryption": [
    {
      "controlId": "ws-2.1.1",
      "controlTitle": "Device Security Standards",
      "certName": "sfc-workspace-security",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/opsec/control-domains/physical-environmental": [
    {
      "controlId": "ws-2.1.2",
      "controlTitle": "Device Lifecycle Management",
      "certName": "sfc-workspace-security",
      "header": "Physical Security of Critical Assets",
      "coverage": "partial"
    },
    {
      "controlId": "ws-2.1.4",
      "controlTitle": "Physical and Travel Security",
      "certName": "sfc-workspace-security",
      "header": "Secure Workspace & Travel Security",
      "coverage": "full"
    }
  ],
  "/guides/account_management/discord": [
    {
      "controlId": "ws-3.1.1",
      "controlTitle": "Account Lifecycle Management",
      "certName": "sfc-workspace-security",
      "header": "Roles",
      "coverage": "partial"
    },
    {
      "controlId": "ws-3.1.2",
      "controlTitle": "Multi-Factor Authentication",
      "certName": "sfc-workspace-security",
      "header": "For Individuals - Account Security Checklist",
      "coverage": "partial"
    },
    {
      "controlId": "ws-3.1.3",
      "controlTitle": "Organizational Account Security",
      "certName": "sfc-workspace-security",
      "header": "Server Settings Checklist",
      "coverage": "partial"
    },
    {
      "controlId": "ws-3.1.5",
      "controlTitle": "Access Reviews",
      "certName": "sfc-workspace-security",
      "header": "Regular Reviews",
      "coverage": "partial"
    },
    {
      "controlId": "ws-6.1.2",
      "controlTitle": "Security Offboarding",
      "certName": "sfc-workspace-security",
      "header": "Regular Reviews",
      "coverage": "partial"
    },
    {
      "controlId": "ws-7.1.3",
      "controlTitle": "Third-Party Access Management",
      "certName": "sfc-workspace-security",
      "header": "Integrations",
      "coverage": "partial"
    }
  ],
  "/opsec/control-domains/technical": [
    {
      "controlId": "ws-3.1.2",
      "controlTitle": "Multi-Factor Authentication",
      "certName": "sfc-workspace-security",
      "header": "Two-Factor & Hardware Authentication",
      "coverage": "partial"
    },
    {
      "controlId": "ws-5.1.1",
      "controlTitle": "Network Security",
      "certName": "sfc-workspace-security",
      "header": "Network & Communication Security",
      "coverage": "partial"
    },
    {
      "controlId": "ws-5.1.2",
      "controlTitle": "Secure Communications",
      "certName": "sfc-workspace-security",
      "header": "Network & Communication Security",
      "coverage": "partial"
    }
  ],
  "/awareness/cultivating-a-security-aware-mindset": [
    {
      "controlId": "ws-3.1.4",
      "controlTitle": "Credential Management Standards",
      "certName": "sfc-workspace-security",
      "header": "Password Management",
      "coverage": "partial"
    }
  ],
  "/guides/account_management/telegram": [
    {
      "controlId": "ws-3.1.4",
      "controlTitle": "Credential Management Standards",
      "certName": "sfc-workspace-security",
      "header": "Account Security Checklist",
      "coverage": "partial"
    },
    {
      "controlId": "ws-5.1.2",
      "controlTitle": "Secure Communications",
      "certName": "sfc-workspace-security",
      "header": "Use Secret Chats for Enhanced Privacy",
      "coverage": "partial"
    }
  ],
  "/guides/account_management/github": [
    {
      "controlId": "ws-4.1.2",
      "controlTitle": "Source Code and Repository Security",
      "certName": "sfc-workspace-security",
      "header": "Repository Settings",
      "coverage": "full"
    }
  ],
  "/opsec/control-domains/people": [
    {
      "controlId": "ws-6.1.1",
      "controlTitle": "Security Onboarding",
      "certName": "sfc-workspace-security",
      "header": "Personnel Security Measures",
      "coverage": "partial"
    },
    {
      "controlId": "ws-6.1.3",
      "controlTitle": "Security Awareness and Training",
      "certName": "sfc-workspace-security",
      "header": "Security Training & Culture",
      "coverage": "partial"
    },
    {
      "controlId": "ws-7.1.2",
      "controlTitle": "Insider Threat Assessment",
      "certName": "sfc-workspace-security",
      "header": "Insider-Threat Mitigation",
      "coverage": "partial"
    }
  ],
  "/awareness/understanding-threat-vectors": [
    {
      "controlId": "ws-6.1.2",
      "controlTitle": "Security Offboarding",
      "certName": "sfc-workspace-security",
      "header": null,
      "coverage": "partial"
    }
  ],
  "/awareness/staying-informed-and-continuous-learning": [
    {
      "controlId": "ws-6.1.3",
      "controlTitle": "Security Awareness and Training",
      "certName": "sfc-workspace-security",
      "header": "Comprehensive Security Training Framework",
      "coverage": "partial"
    }
  ],
  "/opsec/appendices/case-studies": [
    {
      "controlId": "ws-6.1.3",
      "controlTitle": "Security Awareness and Training",
      "certName": "sfc-workspace-security",
      "header": null,
      "coverage": "partial"
    },
    {
      "controlId": "ws-7.1.1",
      "controlTitle": "Workspace Security Monitoring and Incident Response",
      "certName": "sfc-workspace-security",
      "header": "Tabletop Exercises",
      "coverage": "partial"
    }
  ]
};
