// This file is auto-generated by the tags preprocessor
const contributorsIndex = {
  "John Doe": {
    "chapters": [
      "community-management/index.html"
    ]
  },
  "Matt": {
    "chapters": [
      "community-management/index.html"
    ],
    "github": "https://github.com/matta",
    "avatar": "https://github.com/matta.png"
  },
  "Steven": {
    "chapters": [
      "community-management/index.html"
    ],
    "github": "https://github.com/steven",
    "avatar": "https://github.com/steven.png"
  }
};
