// This file is auto-generated by the tags preprocessor
const contributorsIndex = {
  "Matta": {
    "chapters": [
      "community-management/index.html"
    ],
    "github": "https://github.com/mattaereal",
    "avatar": "https://github.com/mattaereal.png"
  },
  "NFTDrewww": {
    "chapters": [
      "community-management/index.html"
    ]
  }
};
