name: Markdown linter

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
      continue-on-error: true
      with:
        globs: |
          docs/**/*.mdx
