name: Markdown linter

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v20
      continue-on-error: true
      with:
        globs: |
          src/**/*.md
