name: 🥢 Spell check 

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  spellcheck:
    name: 🥢 Spell check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: './cspell.json'
          files: |
            src/**/*.md
            *.md
            plugin/**/*.md
          inline: warning
          strict: true
          incremental_files_only: false
